using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Oracle.Generators;

[Generator]
public sealed class ProphecyCatalogGenerator : IIncrementalGenerator
{
    private const string ProphecyFileName = "prophecies.txt";
    // Diagnostic descriptor for malformed lines (warnings, not errors – build can continue).
    private static readonly DiagnosticDescriptor MalformedLineDescriptor = new DiagnosticDescriptor(
        id: "ORCL001",
        title: "Malformed prophecy line",
        messageFormat: "Line '{0}' is malformed, expected format 'Kind|Text'",
        category: "ProphecyGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);
    private static readonly DiagnosticDescriptor UnknownKindDescriptor = new DiagnosticDescriptor(
        id: "ORCL002",
        title: "Unknown prophecy kind",
        messageFormat: "Prophecy kind '{0}' is not recognized, expected 'Affirmative', 'NonCommittal' or 'Negative'",
        category: "ProphecyGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find any AdditionalText files ending with the expected name.
        var prophecyFiles = context.AdditionalTextsProvider
            .Where(at => at.Path.EndsWith(ProphecyFileName, StringComparison.OrdinalIgnoreCase))
            .Select((at, ct) => at.GetText(ct)?.ToString() ?? string.Empty);

        // Collect all matching files (normally only one).
        var allContent = prophecyFiles.Collect();

        // Register the source output.
        context.RegisterSourceOutput(allContent, Execute);
    }

    private static void Execute(SourceProductionContext spc, ImmutableArray<string> allFiles)
    {
        var prophecies = new List<(string Kind, string Text)>();
        var lineNumber = 0;
        foreach (var fileContent in allFiles)
        {
            using var reader = new System.IO.StringReader(fileContent);
            string line;
            while ((line = reader.ReadLine()) != null)
            {
                lineNumber++;
                var trimmed = line.Trim();
                if (trimmed.Length == 0 || trimmed.StartsWith("//", StringComparison.Ordinal)) continue;
                var parts = trimmed.Split(new[] { '|' }, 2);
                if (parts.Length != 2)
                {
                    // Report a warning diagnostic for the malformed line.
                    var diag = Diagnostic.Create(MalformedLineDescriptor, Location.None, trimmed);
                    spc.ReportDiagnostic(diag);
                    continue;
                }
                var kind = parts[0].Trim();
                var text = parts[1].Trim();
                // Verify the kind string is one of the expected values.
                if (kind != "Affirmative" && kind != "NonCommittal" && kind != "Negative")
                {
                    var diag = Diagnostic.Create(UnknownKindDescriptor, Location.None, kind);
                    spc.ReportDiagnostic(diag);
                }
                prophecies.Add((kind, text));
            }
        }

        // Build the generated source.
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("namespace Oracle.Core");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ProphecyCatalog");
        sb.AppendLine("    {");
        sb.AppendLine("        public static ImmutableArray<Prophecy> All { get; } = ImmutableArray.Create(");
        for (int i = 0; i < prophecies.Count; i++)
        {
            var (kindStr, text) = prophecies[i];
            var enumValue = kindStr switch
            {
                "Affirmative" => "ProphecyKind.Affirmative",
                "NonCommittal" => "ProphecyKind.NonCommittal",
                "Negative" => "ProphecyKind.Negative",
                _ => "ProphecyKind.NonCommittal"
            };
            var escaped = text.Replace("\"", "\\\"");
            sb.Append($"            new Prophecy(\"{escaped}\", {enumValue})");
            sb.Append(i < prophecies.Count - 1 ? "," : string.Empty);
            sb.AppendLine();
        }
        sb.AppendLine("        );");
        sb.AppendLine();
        sb.AppendLine("        public static ImmutableArray<Prophecy> ByKind(ProphecyKind kind) =>");
        sb.AppendLine("            All.Where(p => p.Kind == kind).ToImmutableArray();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("ProphecyCatalog.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
